demo/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView

from demo import views


urlpatterns = [
    url(
        r"^$",
        TemplateView.as_view(template_name="demo/home.html"),
        name="home"
    ),
    url(
        r"^all-users/$",
        views.AllUsersView.as_view(),
        name="all-users"
    ),
    url(
        r"^anonymous-only/$",
        views.AnonymousOnlyView.as_view(),
        name="anonymous-only"
    ),
    url(
        r"^anonymous-and-authenticated/$",
        views.AnonymousAndAuthenticatedView.as_view(),
        name="anonymous-and-authenticated"
    ),
    url(
        r"^per-user/$",
        views.PerUserView.as_view(),
        name="per-user"
    ),
    url(
        r"^modify/(?P<pk>\d+)/$",
        views.modify_trivial_content,
        name="modify-trivial-content"
    ),
]

project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

import rest_framework_extras
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework import routers, serializers, viewsets
from formfactory import api as formfactory_api
from jmbo.admin import ModelBaseAdmin, ModelBaseAdminForm
from jmbo import api as jmbo_api
from listing import api as listing_api
from post import api as post_api


router = routers.DefaultRouter()

rest_framework_extras.discover(router)
rest_framework_extras.register(router)

# Register jmbo suite routers
formfactory_api.register(router)
jmbo_api.register(router)
listing_api.register(router)
post_api.register(router)

admin.autodiscover()

urlpatterns = [
    url(r"^", include("demo.urls", namespace="demo")),
    url(r"^mobius/", include("mobius.urls", namespace="mobius")),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^api/(?P<version>(v1))/", include(router.urls)),
    url(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    url(r"^api-auth/$", obtain_jwt_token, name="obtain_token"),
    url(r"^auth/", include("django.contrib.auth.urls", namespace="auth")),
    url(
        r"^formfactory/",
        include("formfactory.urls", namespace="formfactory")
    ),
    url(r"^jmbo/", include("jmbo.urls", namespace="jmbo")),
    url(r"^link/", include("link.urls", namespace="link")),
    url(r"^listing/", include("listing.urls", namespace="listing")),
    url(r"^mote/", include("mote.urls", namespace="mote")),
    url(r"^navbuilder/", include("navbuilder.urls", namespace="navbuilder")),
    url(r"^post/", include("post.urls", namespace="post")),

    # Comments can't handle namespaces
    url(r"^comments/", include("django_comments.urls")),
    url(r"^nested_admin/", include("nested_admin.urls")),
]

if settings.DEBUG:
    # Host our own media
    urlpatterns += [
        url(
            r"^media/(?P<path>.*)$",
            serve,
            {"document_root": settings.MEDIA_ROOT, "show_indexes": True}
        ),
    ]
    # Expose Django Debug Toolbar if we can import it
    try:
        import debug_toolbar
        urlpatterns += [
            url(r"^__debug__/", include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

demo/models.py
from jmbo.models import ModelBase


class TrivialContent(ModelBase):
    """We need one model so South migrations can be initiated."""
    pass

demo/forms.py
from django import forms


class TestForm(forms.Form):
    name = forms.CharField()

demo/views.py
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from ultracache.decorators import cached_get
from demo.forms import TestForm
from demo.models import TrivialContent


class TestView(FormView):
    template_name = "demo/test_view.html"
    form_class = TestForm


# Four views to illustrate django-ultracache and django-cache-headers working
# together.

@method_decorator(
    cached_get(600), name="get"
)
class AllUsersView(TemplateView):
    template_name = "demo/all_users_view.html"

    def get_context_data(self, **kwargs):
        di = super(AllUsersView, self).get_context_data(**kwargs)
        di["object"] = TrivialContent.objects.get(slug="all-users")
        return di


# We can't use the cached_get decorator because the view  may not be cached for
# authenticated users. We need to use template fragment caching.
class AnonymousOnlyView(TemplateView):
    template_name = "demo/anonymous_only_view.html"

    def get_context_data(self, **kwargs):
        di = super(AnonymousOnlyView, self).get_context_data(**kwargs)
        di["object"] = TrivialContent.objects.get(slug="anonymous-only")
        return di


@method_decorator(
    cached_get(600, "request.user.is_authenticated()"), name="get"
)
class AnonymousAndAuthenticatedView(TemplateView):
    template_name = "demo/anonymous_and_authenticated_view.html"

    def get_context_data(self, **kwargs):
        di = super(AnonymousAndAuthenticatedView, self).get_context_data(**kwargs)
        di["object"] = TrivialContent.objects.get(slug="anonymous-and-authenticated")
        return di


@method_decorator(
    cached_get(600, "request.user.id"), name="get"
)
class PerUserView(TemplateView):
    template_name = "demo/per_user_view.html"

    def get_context_data(self, **kwargs):
        di = super(PerUserView, self).get_context_data(**kwargs)
        di["object"] = TrivialContent.objects.get(slug="per-user")
        return di


def modify_trivial_content(request, pk):
    """Trivial modification to trigger ultracache expiration"""

    TrivialContent.objects.get(pk=pk).save()
    return HttpResponse("Modified %s" % pk)

demo/templates/base.html
<!doctype html>
{% if composer_slots %}
    {% load composer_tags %}
{% endif %}
{% comment %}
    ATM a very basic template to show the slots in action.
    Note the sidebar slot that can be switched on/off at will.
{% endcomment %}

<body>
    <div id="header">
        {% if composer_slots.header %}
            {% composer header %}
        {% else %}
            Header slot: to populate this, add a header slot with url '/'
        {% endif %}
    </div>
    <div id="content"{% if not composer_slots.sidebar %} class="wide"{% endif %}>
        {% block content %}
        {% if composer_slots.content %}
            {% composer content %}
        {% else %}
            Content slot: to populate this, add a content slot with url '/'
        {% endif %}
        {% endblock %}
    </div>
    {% if composer_slots.sidebar %}
        <div id="sidebar">
            {% composer sidebar %}
        </div>
    {% endif %}
    <div id="footer">
        {% if composer_slots.footer %}
            {% composer footer %}
        {% else %}
            Footer slot: to populate this, add a footer slot with url '/'
        {% endif %}
    </div>
</body>

demo/templates/composer/inclusion_tags/content.html
This content slot has no rows assigned to it.

demo/templates/composer/inclusion_tags/footer.html
This footer slot has no rows assigned to it.

demo/templates/composer/inclusion_tags/header.html
This header slot has no rows assigend to it.

demo/templates/demo/all_users_view.html
This view was rendered on {% now "jS F Y H:i:s" %}<br />
This view is cached for all users.<br />
object = {{ object.title }}<br />
To expire this page edit the Trivial Content object called {{ object.title }} <a href="{% url "demo:modify-trivial-content" 1 %}">now</a>.

demo/templates/demo/anonymous_and_authenticated_view.html
This view was rendered on {% now "jS F Y H:i:s" %}<br />
This view is cached once for anonymous users and once for authenticated users.<br />
{% if request.user.is_anonymous %}
    You are anonymous
{% else %}
    You are authenticated.
{% endif %}
<br />
object = {{ object.title }}<br />
To expire this page edit the Trivial Content object called {{ object.title }}  <a href="{% url "demo:modify-trivial-content" 3 %}">now</a>.

demo/templates/demo/anonymous_only_view.html
{% load ultracache_tags %}

{% if request.user.is_anonymous %}
    {% ultracache 600 "anonymous-only" %}
        This view was rendered on {% now "jS F Y H:i:s" %}<br />
        This view is cached only for anonymous users.<br />
        You are anonymous<br />
        object = {{ object.title }}
    {% endultracache %}
{% else %}
    This view was rendered on {% now "jS F Y H:i:s" %}<br />
    This view is cached only for anonymous users.<br />
    You are logged in as {{ request.user.id }}<br />
    object = {{ object.title }}
{% endif %}

<br />
To expire this page edit the Trivial Content object called {{ object.title }} <a href="{% url "demo:modify-trivial-content" 2 %}">now</a>.

demo/templates/demo/home.html
{% load mobius_tags %}
{% load render_bundle from webpack_loader %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Mobius Skeleton</title>

    {% if_has_bundle "style" "css" %}
        {% render_bundle "style" "css" %}
    {% end_if_has_bundle %}
</head>
<body>
    <h1>Mobius Skeleton</h1>

    {% if_has_bundle "main" "js" %}
        {% render_bundle "main" "js" %}
    {% end_if_has_bundle %}
</body>
</html>

demo/templates/demo/per_user_view.html
This view was rendered on {% now "jS F Y H:i:s" %}<br />
This view is cached per user.<br />
You are logged in as {{ request.user.id }}<br />
object = {{ object.title }}<br />
To expire this page edit the Trivial Content object called {{ object.title }} <a href="{% url "demo:modify-trivial-content" 4 %}">now</a>.

demo/templates/demo/radmin.html
{% load mobius_tags %}
{% load render_bundle from webpack_loader %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Radmin</title>

    {% if_has_bundle "style" "css" %}
        {% render_bundle "style" "css" %}
    {% end_if_has_bundle %}
</head>
<body>
    <div id="radmin"></div>
    {% if_has_bundle "main" "js" %}
        {% render_bundle "main" "js" %}
    {% end_if_has_bundle %}
</body>
</html>

demo/templates/demo/test_view.html
{% extends "base.html" %}

{% block content %}
    {{ form }}
{% endblock %}